### ISSUE TITLE
das wirkt sich auch auf den weiter button aus sodass die validierung noch nicht funktionstüchtig ist, also man kann weiter machen ohne korrekte eingaben

### ISSUE THREAD

**Issue by BraunJonas** [wwi21seb-projekt/Client_BubbleMatee#9]
Bei der Registrierung scheint die Überprüfung der Mail und des Nutzernamens kein passendes Feedback zu geben. Vielleicht nochmal überarbeiten, damit Punkt 7 der UI Checkliste erfüllt ist.
![Uploading MicrosoftTeams-image (13).png…]()

_Originally posted by @pbahde in https://github.com/wwi21seb-projekt/Client_BubbleMatee/issues/7#issuecomment-1854546580_

**Comment by zimmerai** [comment]
Passt 👍 danke dir Jonas 🫶
